version: '3'
services:
  web:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data:/data/db
